import type { GlobalThemeConfig, ComponentOverrides } from './theme-config.model';
import { configToCssVariables } from './angular-material-tokens';

/**
 * Generates a full CSS file string with :root block for global tokens
 * and optional scoped blocks for per-component overrides.
 */
export function generateThemeCss(
  globalConfig: GlobalThemeConfig,
  componentOverrides: ComponentOverrides
): string {
  const globalVars = configToCssVariables(globalConfig);
  const rootBlock = `:root {\n  ${globalVars.replace(/\n/g, '\n  ')}\n}`;

  const overrideBlocks: string[] = [];
  for (const [componentId, tokens] of Object.entries(componentOverrides)) {
    if (Object.keys(tokens).length === 0) continue;
    const selector = `.mat-theme-override-${componentId}`;
    const props = Object.entries(tokens)
      .map(([key, value]) => {
        const cssVar = tokenKeyToCssVar(componentId, key);
        return `  ${cssVar}: ${typeof value === 'number' ? value + 'px' : value};`;
      })
      .join('\n');
    overrideBlocks.push(`${selector} {\n${props}\n}`);
  }

  const comment = `/* Angular Material Theme - Generated by Material Theme Customizer
   How to use: Import this file in your Angular project:
   - In angular.json: add "material-theme.css" to the "styles" array, or
   - In styles.scss: @import 'path/to/material-theme.css';
   Then your Angular Material components will use these tokens. */\n\n`;
  return comment + rootBlock + (overrideBlocks.length ? '\n\n' + overrideBlocks.join('\n\n') : '') + '\n';
}

function tokenKeyToCssVar(componentId: string, key: string): string {
  const kebab = key.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '');
  return `--mat-${componentId}-${kebab}`;
}
