import type { GlobalThemeConfig, ComponentOverrides } from './theme-config.model';
import { configToCssVariables } from './angular-material-tokens';

/**
 * Generates an SCSS file that sets Angular Material system tokens via CSS custom properties.
 * Import in your Angular project (e.g. in styles.scss). Component overrides are output
 * as scoped selectors that set component-specific tokens.
 */
export function generateThemeScss(
  globalConfig: GlobalThemeConfig,
  componentOverrides: ComponentOverrides
): string {
  const vars = configToCssVariables(globalConfig);
  const lines: string[] = [
    '/* Angular Material Theme - Generated by Material Theme Customizer */',
    '/* Import in styles.scss: @use \'path/to/material-theme\' as theme; */',
    '',
    ':root {',
    '  ' + vars.replace(/\n/g, '\n  '),
    '}',
    '',
  ];

  for (const [componentId, tokens] of Object.entries(componentOverrides)) {
    if (Object.keys(tokens).length === 0) continue;
    const selector = `.mat-theme-override-${componentId}`;
    const props = Object.entries(tokens)
      .map(([key, value]) => {
        const kebab = key.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '');
        return `  --mat-${componentId}-${kebab}: ${typeof value === 'number' ? value + 'px' : value};`;
      })
      .join('\n');
    lines.push(`${selector} {`);
    lines.push(props);
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n') + '\n';
}
